import { Enemy, Platform } from './types'
import { GAME_WIDTH, GAME_HEIGHT, PLATFORM_HEIGHT, ENEMY_SIZE } from './gameLogic'

export interface Level {
  number: number
  name: string
  platforms: Platform[]
  enemies: Enemy[]
  playerStartX: number
  playerStartY: number
}

export const LEVELS: Level[] = [
  {
    number: 1,
    name: 'Veggie Valley',
    playerStartX: 50,
    playerStartY: GAME_HEIGHT - 100,
    platforms: [
      { x: 0, y: GAME_HEIGHT - 50, width: GAME_WIDTH, height: PLATFORM_HEIGHT },
      { x: 100, y: 450, width: 150, height: PLATFORM_HEIGHT },
      { x: 350, y: 380, width: 200, height: PLATFORM_HEIGHT },
      { x: 600, y: 310, width: 150, height: PLATFORM_HEIGHT },
      { x: 250, y: 240, width: 180, height: PLATFORM_HEIGHT },
      { x: 500, y: 170, width: 150, height: PLATFORM_HEIGHT },
    ],
    enemies: [
      {
        id: '1',
        x: 150,
        y: 400,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 100,
        patrolEnd: 220,
      },
      {
        id: '2',
        x: 400,
        y: 330,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 350,
        patrolEnd: 520,
      },
      {
        id: '3',
        x: 630,
        y: 260,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 600,
        patrolEnd: 720,
      },
      {
        id: '4',
        x: 280,
        y: 190,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 250,
        patrolEnd: 400,
      },
      {
        id: '5',
        x: 540,
        y: 120,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 500,
        patrolEnd: 620,
      },
    ],
  },
  {
    number: 2,
    name: 'Broccoli Bridge',
    playerStartX: 50,
    playerStartY: GAME_HEIGHT - 100,
    platforms: [
      { x: 0, y: GAME_HEIGHT - 50, width: 200, height: PLATFORM_HEIGHT },
      { x: 300, y: GAME_HEIGHT - 50, width: 200, height: PLATFORM_HEIGHT },
      { x: 600, y: GAME_HEIGHT - 50, width: 200, height: PLATFORM_HEIGHT },
      { x: 150, y: 420, width: 120, height: PLATFORM_HEIGHT },
      { x: 350, y: 350, width: 120, height: PLATFORM_HEIGHT },
      { x: 550, y: 280, width: 120, height: PLATFORM_HEIGHT },
      { x: 200, y: 210, width: 150, height: PLATFORM_HEIGHT },
      { x: 450, y: 140, width: 150, height: PLATFORM_HEIGHT },
    ],
    enemies: [
      {
        id: '1',
        x: 100,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 0,
        patrolEnd: 180,
      },
      {
        id: '2',
        x: 350,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 300,
        patrolEnd: 480,
      },
      {
        id: '3',
        x: 180,
        y: 370,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 150,
        patrolEnd: 250,
      },
      {
        id: '4',
        x: 400,
        y: 300,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 350,
        patrolEnd: 450,
      },
      {
        id: '5',
        x: 580,
        y: 230,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 550,
        patrolEnd: 650,
      },
      {
        id: '6',
        x: 250,
        y: 160,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 200,
        patrolEnd: 330,
      },
    ],
  },
  {
    number: 3,
    name: 'Floret Fortress',
    playerStartX: 50,
    playerStartY: GAME_HEIGHT - 100,
    platforms: [
      { x: 0, y: GAME_HEIGHT - 50, width: 250, height: PLATFORM_HEIGHT },
      { x: 550, y: GAME_HEIGHT - 50, width: 250, height: PLATFORM_HEIGHT },
      { x: 250, y: 450, width: 100, height: PLATFORM_HEIGHT },
      { x: 450, y: 450, width: 100, height: PLATFORM_HEIGHT },
      { x: 150, y: 370, width: 120, height: PLATFORM_HEIGHT },
      { x: 530, y: 370, width: 120, height: PLATFORM_HEIGHT },
      { x: 320, y: 290, width: 160, height: PLATFORM_HEIGHT },
      { x: 100, y: 210, width: 140, height: PLATFORM_HEIGHT },
      { x: 560, y: 210, width: 140, height: PLATFORM_HEIGHT },
      { x: 300, y: 130, width: 200, height: PLATFORM_HEIGHT },
    ],
    enemies: [
      {
        id: '1',
        x: 120,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 0,
        patrolEnd: 230,
      },
      {
        id: '2',
        x: 620,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 550,
        patrolEnd: 780,
      },
      {
        id: '3',
        x: 280,
        y: 400,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 250,
        patrolEnd: 330,
      },
      {
        id: '4',
        x: 480,
        y: 400,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 450,
        patrolEnd: 530,
      },
      {
        id: '5',
        x: 180,
        y: 320,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 150,
        patrolEnd: 250,
      },
      {
        id: '6',
        x: 580,
        y: 320,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 530,
        patrolEnd: 630,
      },
      {
        id: '7',
        x: 380,
        y: 240,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 320,
        patrolEnd: 460,
      },
    ],
  },
  {
    number: 4,
    name: 'Green Gauntlet',
    playerStartX: 50,
    playerStartY: GAME_HEIGHT - 100,
    platforms: [
      { x: 0, y: GAME_HEIGHT - 50, width: 150, height: PLATFORM_HEIGHT },
      { x: 200, y: GAME_HEIGHT - 50, width: 100, height: PLATFORM_HEIGHT },
      { x: 350, y: GAME_HEIGHT - 50, width: 100, height: PLATFORM_HEIGHT },
      { x: 500, y: GAME_HEIGHT - 50, width: 100, height: PLATFORM_HEIGHT },
      { x: 650, y: GAME_HEIGHT - 50, width: 150, height: PLATFORM_HEIGHT },
      { x: 100, y: 430, width: 100, height: PLATFORM_HEIGHT },
      { x: 275, y: 380, width: 100, height: PLATFORM_HEIGHT },
      { x: 425, y: 380, width: 100, height: PLATFORM_HEIGHT },
      { x: 600, y: 430, width: 100, height: PLATFORM_HEIGHT },
      { x: 175, y: 310, width: 100, height: PLATFORM_HEIGHT },
      { x: 350, y: 280, width: 100, height: PLATFORM_HEIGHT },
      { x: 525, y: 310, width: 100, height: PLATFORM_HEIGHT },
      { x: 250, y: 210, width: 120, height: PLATFORM_HEIGHT },
      { x: 430, y: 210, width: 120, height: PLATFORM_HEIGHT },
      { x: 340, y: 130, width: 120, height: PLATFORM_HEIGHT },
    ],
    enemies: [
      {
        id: '1',
        x: 50,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 0,
        patrolEnd: 130,
      },
      {
        id: '2',
        x: 230,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 200,
        patrolEnd: 280,
      },
      {
        id: '3',
        x: 380,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 350,
        patrolEnd: 430,
      },
      {
        id: '4',
        x: 530,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 500,
        patrolEnd: 580,
      },
      {
        id: '5',
        x: 130,
        y: 380,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 100,
        patrolEnd: 180,
      },
      {
        id: '6',
        x: 305,
        y: 330,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 275,
        patrolEnd: 355,
      },
      {
        id: '7',
        x: 455,
        y: 330,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 425,
        patrolEnd: 505,
      },
      {
        id: '8',
        x: 630,
        y: 380,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 600,
        patrolEnd: 680,
      },
    ],
  },
  {
    number: 5,
    name: 'Crown of Cruciferous',
    playerStartX: 50,
    playerStartY: GAME_HEIGHT - 100,
    platforms: [
      { x: 0, y: GAME_HEIGHT - 50, width: 180, height: PLATFORM_HEIGHT },
      { x: 620, y: GAME_HEIGHT - 50, width: 180, height: PLATFORM_HEIGHT },
      { x: 280, y: 480, width: 240, height: PLATFORM_HEIGHT },
      { x: 100, y: 400, width: 100, height: PLATFORM_HEIGHT },
      { x: 600, y: 400, width: 100, height: PLATFORM_HEIGHT },
      { x: 250, y: 340, width: 80, height: PLATFORM_HEIGHT },
      { x: 470, y: 340, width: 80, height: PLATFORM_HEIGHT },
      { x: 360, y: 280, width: 80, height: PLATFORM_HEIGHT },
      { x: 150, y: 240, width: 100, height: PLATFORM_HEIGHT },
      { x: 550, y: 240, width: 100, height: PLATFORM_HEIGHT },
      { x: 280, y: 180, width: 100, height: PLATFORM_HEIGHT },
      { x: 420, y: 180, width: 100, height: PLATFORM_HEIGHT },
      { x: 340, y: 100, width: 120, height: PLATFORM_HEIGHT },
    ],
    enemies: [
      {
        id: '1',
        x: 80,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 0,
        patrolEnd: 160,
      },
      {
        id: '2',
        x: 680,
        y: 500,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 620,
        patrolEnd: 780,
      },
      {
        id: '3',
        x: 350,
        y: 430,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 280,
        patrolEnd: 500,
      },
      {
        id: '4',
        x: 130,
        y: 350,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 100,
        patrolEnd: 180,
      },
      {
        id: '5',
        x: 630,
        y: 350,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 600,
        patrolEnd: 680,
      },
      {
        id: '6',
        x: 280,
        y: 290,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 250,
        patrolEnd: 310,
      },
      {
        id: '7',
        x: 500,
        y: 290,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 470,
        patrolEnd: 530,
      },
      {
        id: '8',
        x: 390,
        y: 230,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 360,
        patrolEnd: 420,
      },
      {
        id: '9',
        x: 180,
        y: 190,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: 1,
        patrolStart: 150,
        patrolEnd: 230,
      },
      {
        id: '10',
        x: 580,
        y: 190,
        width: ENEMY_SIZE,
        height: ENEMY_SIZE,
        velocityX: 0,
        velocityY: 0,
        direction: -1,
        patrolStart: 550,
        patrolEnd: 630,
      },
    ],
  },
]
